## Path Loss Prediction Based On SVR Algorithm

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set(color_codes=True)

In [2]:
# Import dataset 

bus_way = pd.read_excel('BusWay.xlsx')

In [3]:
bus_way

,Koridor_No,Koridor,No.,Longitude_of_User,Latitude_of_User,DateTime,Serving RSRP_All Logs,Serving RSSI_All Logs,PCC PUSCH Path Loss_All Logs,LTE Serving Cell Distance (m),Frequency (MHz),Total_Heigh_of_TX (m),Total_Heigh_of_RX (m),Lebar Jalan (m),Tinggi Gedung Sekitar (m),Jarak Antar Gedung (m),PUCCH Path Loss_All Logs
0,1_7890,1,7890,104.760751,-2.987531,2020-10-25 14:32:26.500,-59.78,-31.55,,18.81,1800,1818.81,3618.81,21.27,10,1,78
1,1_7892,1,7892,104.760764,-2.987551,2020-10-25 14:32:27.500,-56.75,-29.52,77,17.48,1800,1817.48,3617.48,21.27,10,1,79
2,1_7894,1,7894,104.760778,-2.987570,2020-10-25 14:32:28.500,-57.11,-29.36,78,16.43,1800,1816.43,3616.43,21.27,10,1,78
3,1_7896,1,7896,104.760791,-2.987590,2020-10-25 14:32:29.500,-65.77,-35.88,80,15.81,1800,1815.81,3615.81,21.27,10,1,85
4,1_7898,1,7898,104.760806,-2.987610,2020-10-25 14:32:30.500,-62.61,-33.25,80,15.50,1800,1815.50,3615.50,21.27,10,1,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71089,1_84684,1,84684,104.682087,-2.915972,2020-11-01 17:12:34.500,-90.81,-63.08,106,505.82,1800,2305.82,4105.82,24.32,10,3,106
71090,1_84686,1,84686,104.682087,-2.915972,2020-11-01 17:12:35.500,-93.21,-64.75,112,505.82,1800,2305.82,4105.82,24.32,10,3,112
71091,1_84688,1,84688,104.682087,-2.915972,2020-11-01 17:12:36.500,-89.02,-61.17,110,505.82,1800,2305.82,4105.82,24.32,10,3,110
71092,1_84690,1,84690,104.682087,-2.915972,2020-11-01 17:12:37.500,-85.33,-58.69,104,505.82,1800,2305.82,4105.82,24.32,10,3,104
71093,1_84692,1,84692,104.682087,-2.915972,2020-11-01 17:12:38.500,-86.75,-59.81,,505.82,1800,2305.82,4105.82,24.32,10,3,104

In [4]:
# Membuang kolom yang tidak diperlukan
bus_way = bus_way.drop(['Koridor_No', 'Koridor', 'No.', 'Longitude_of_User', 'Latitude_of_User', 'DateTime', 
                   'Serving RSRP_All Logs', 'Serving RSSI_All Logs', 'PCC PUSCH Path Loss_All Logs'], axis=1)
bus_way

,LTE Serving Cell Distance (m),Frequency (MHz),Total_Heigh_of_TX (m),Total_Heigh_of_RX (m),Lebar Jalan (m),Tinggi Gedung Sekitar (m),Jarak Antar Gedung (m),PUCCH Path Loss_All Logs
0,18.81,1800,1818.81,3618.81,21.27,10,1,78
1,17.48,1800,1817.48,3617.48,21.27,10,1,79
2,16.43,1800,1816.43,3616.43,21.27,10,1,78
3,15.81,1800,1815.81,3615.81,21.27,10,1,85
4,15.50,1800,1815.50,3615.50,21.27,10,1,83
...,...,...,...,...,...,...,...,...
71089,505.82,1800,2305.82,4105.82,24.32,10,3,106
71090,505.82,1800,2305.82,4105.82,24.32,10,3,112
71091,505.82,1800,2305.82,4105.82,24.32,10,3,110
71092,505.82,1800,2305.82,4105.82,24.32,10,3,104
71093,505.82,1800,2305.82,4105.82,24.32,10,3,104

In [5]:
bus_way = bus_way.reset_index()
bus_way

,index,LTE Serving Cell Distance (m),Frequency (MHz),Total_Heigh_of_TX (m),Total_Heigh_of_RX (m),Lebar Jalan (m),Tinggi Gedung Sekitar (m),Jarak Antar Gedung (m),PUCCH Path Loss_All Logs
0,0,18.81,1800,1818.81,3618.81,21.27,10,1,78
1,1,17.48,1800,1817.48,3617.48,21.27,10,1,79
2,2,16.43,1800,1816.43,3616.43,21.27,10,1,78
3,3,15.81,1800,1815.81,3615.81,21.27,10,1,85
4,4,15.50,1800,1815.50,3615.50,21.27,10,1,83
...,...,...,...,...,...,...,...,...,...
71089,71089,505.82,1800,2305.82,4105.82,24.32,10,3,106
71090,71090,505.82,1800,2305.82,4105.82,24.32,10,3,112
71091,71091,505.82,1800,2305.82,4105.82,24.32,10,3,110
71092,71092,505.82,1800,2305.82,4105.82,24.32,10,3,104
71093,71093,505.82,1800,2305.82,4105.82,24.32,10,3,104

In [6]:
# Menghapus banyaknya data yang lebih dari 20000 berdasarkan kolom dari kolom "indeks" yang dibuat

removeData = bus_way[(bus_way['index']) >= 20000].index
bus_way.drop(removeData, inplace = True)
bus_way = bus_way.drop(['index'], axis=1)
bus_way

,LTE Serving Cell Distance (m),Frequency (MHz),Total_Heigh_of_TX (m),Total_Heigh_of_RX (m),Lebar Jalan (m),Tinggi Gedung Sekitar (m),Jarak Antar Gedung (m),PUCCH Path Loss_All Logs
0,18.81,1800,1818.81,3618.81,21.27,10,1,78
1,17.48,1800,1817.48,3617.48,21.27,10,1,79
2,16.43,1800,1816.43,3616.43,21.27,10,1,78
3,15.81,1800,1815.81,3615.81,21.27,10,1,85
4,15.50,1800,1815.50,3615.50,21.27,10,1,83
...,...,...,...,...,...,...,...,...
19995,73.42,2100,2173.42,4273.42,23.32,15,1,114
19996,60.59,1800,1860.59,3660.59,23.32,15,1,96
19997,75.85,2100,2175.85,4275.85,23.32,15,1,115
19998,70.91,1800,1870.91,3670.91,23.32,15,1,101
19999,88.06,2100,2188.06,4288.06,23.32,15,1,104

### EKSPLORASI DATA

In [7]:
# Hitung banyaknya baris pada dataset
bus_way.count()

LTE Serving Cell Distance (m)    20000
Frequency (MHz)                  20000
Total_Heigh_of_TX (m)            20000
Total_Heigh_of_RX (m)            20000
Lebar Jalan (m)                  20000
Tinggi Gedung Sekitar (m)        20000
Jarak Antar Gedung (m)           20000
PUCCH Path Loss_All Logs         20000
dtype: int64

In [8]:
# Cek masing - masing tipe data
bus_way.dtypes

LTE Serving Cell Distance (m)    float64
Frequency (MHz)                    int64
Total_Heigh_of_TX (m)            float64
Total_Heigh_of_RX (m)            float64
Lebar Jalan (m)                  float64
Tinggi Gedung Sekitar (m)          int64
Jarak Antar Gedung (m)             int64
PUCCH Path Loss_All Logs           int64
dtype: object

In [9]:
# Menghitung jumlah baris dan kolom pada dataset
bus_way.shape

(20000, 8)

### Preprocessing

In [10]:
from sklearn.preprocessing import StandardScaler
features = ['LTE Serving Cell Distance (m)', 'Frequency (MHz)', 'Total_Heigh_of_TX (m)', 'Total_Heigh_of_RX (m)', 
            'Lebar Jalan (m)', 'Tinggi Gedung Sekitar (m)', 'Jarak Antar Gedung (m)']

# fitur x (Input)
x = bus_way.loc[:, features].values

# fitur y (Output)
y = bus_way.loc[:, ['PUCCH Path Loss_All Logs']].values

In [11]:
print(x)

[[1.88100e+01 1.80000e+03 1.81881e+03 ... 2.12700e+01 1.00000e+01
  1.00000e+00]
 [1.74800e+01 1.80000e+03 1.81748e+03 ... 2.12700e+01 1.00000e+01
  1.00000e+00]
 [1.64300e+01 1.80000e+03 1.81643e+03 ... 2.12700e+01 1.00000e+01
  1.00000e+00]
 ...
 [7.58500e+01 2.10000e+03 2.17585e+03 ... 2.33200e+01 1.50000e+01
  1.00000e+00]
 [7.09100e+01 1.80000e+03 1.87091e+03 ... 2.33200e+01 1.50000e+01
  1.00000e+00]
 [8.80600e+01 2.10000e+03 2.18806e+03 ... 2.33200e+01 1.50000e+01
  1.00000e+00]]

In [12]:
print(y)

[[ 78]
 [ 79]
 [ 78]
 ...
 [115]
 [101]
 [104]]

In [13]:
# Standardisasi data
scaler = StandardScaler()

# Input
x = scaler.fit_transform(x)
print(x)

[[-0.39677451 -0.8529732  -0.49134558 ... -1.20361375 -1.22193151
   0.        ]
 [-0.39803041 -0.8529732  -0.49254129 ... -1.20361375 -1.22193151
   0.        ]
 [-0.39902192 -0.8529732  -0.49348528 ... -1.20361375 -1.22193151
   0.        ]
 ...
 [-0.34291218  1.17236978 -0.1703554  ... -0.39105138  0.46686886
   0.        ]
 [-0.34757698 -0.8529732  -0.44450604 ... -0.39105138  0.46686886
   0.        ]
 [-0.3313824   1.17236978 -0.15937822 ... -0.39105138  0.46686886
   0.        ]]

In [14]:
# Output
y = scaler.fit_transform(y)
y_sc = pd.DataFrame(data = y, columns = ['PUCCH Path Loss_All Logs'])
print(y_sc)

       PUCCH Path Loss_All Logs
0                     -2.409051
1                     -2.334668
2                     -2.409051
3                     -1.888372
4                     -2.037137
...                         ...
19995                  0.268726
19996                 -1.070162
19997                  0.343109
19998                 -0.698249
19999                 -0.475101

[20000 rows x 1 columns]

### Melakukan PCA untuk reduksi

In [15]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)
principalComponents = pca.fit_transform(x)
principal_bus_way = pd.DataFrame(data = principalComponents, columns = ['Input'])

In [16]:
final_bus_way = pd.concat([principal_bus_way, y_sc], axis=1)
print(final_bus_way)

          Input  PUCCH Path Loss_All Logs
0     -1.121354                 -2.409051
1     -1.123310                 -2.334668
2     -1.124854                 -2.409051
3     -1.125766                 -1.888372
4     -1.126222                 -2.037137
...         ...                       ...
19995  0.120011                  0.268726
19996 -0.952050                 -1.070162
19997  0.123585                  0.343109
19998 -0.936873                 -0.698249
19999  0.141542                 -0.475101

[20000 rows x 2 columns]

### Melakukan splitting data

In [17]:
from sklearn.model_selection import train_test_split

x = final_bus_way.loc[:, ['Input']].values

y = final_bus_way.loc[:, ['PUCCH Path Loss_All Logs']].values

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [19]:
print("x Train Shape :", x_train.shape)
print("x test Shape :", x_test.shape)
print("y train shape :", y_train.shape)
print("y test shape :", y_test.shape)

x Train Shape : (16000, 1)
x test Shape : (4000, 1)
y train shape : (16000, 1)
y test shape : (4000, 1)

### Menentukan Nilai MAPE, RMSE, MAE, MaxPE

In [20]:
# Untuk MAPE

def MAPE(y_actual,y_predicted):
    mape = np.mean(np.abs((y_actual - y_predicted)/y_actual))*100
    return mape

In [21]:
# Untuk RMSE

def RMSE(y_actual, y_predicted):
    subtract = y_predicted - y_actual
    square = subtract ** 2
    mean = square.mean()
    rmse = np.sqrt(mean)
    return rmse

In [22]:
# Untuk MAE

def MAE(y_actual, y_predicted):
    mae = np.mean(abs(y_actual - y_predicted))
    return mae

In [23]:
# Untuk MaxPE

def MaxPE(y_actual, y_predicted):
    maxpe = np.max(y_actual - y_predicted)
    return maxpe

### Model Support Vector Regressor (SVR) untuk mendapatkan hasil MAPE, RMSE, MAE, dan MaxPE

In [24]:
from sklearn.svm import SVR

In [25]:
regressor = SVR(kernel='poly')
svr_model = regressor.fit(x_train, y_train)

svr_pred = svr_model.predict(x_test)

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

In [26]:
# Nilai MAPE
svr_mape = MAPE(y_test, svr_pred)
print("MAPE :", svr_mape, "%")

MAPE : 145.83295212275053 %

In [27]:
# Nilai RMSE
svr_rmse = RMSE(y_test, svr_pred)
print("RMSE :", svr_rmse, "dB")

RMSE : 1.0698626458505012 dB

In [28]:
# Nilai MAE
svr_mae = MAE(y_test, svr_pred)
print("MAE :", svr_mae, "dB")

MAE : 0.8563496523801338 dB

In [29]:
# Nilai MaxPE

svr_maxpe = MaxPE(y_test, svr_pred)
print("MaxPE :", svr_maxpe, "dB")

MaxPE : 2.8773907370397085 dB